[project]
name = "cv-website"
version = "0.1.0"
description = "Static CV website builder"
requires-python = ">=3.11"
dependencies = [
  "pypdf>=4.2.0",
  "cairosvg>=2.7.1",
]

[tool.uv]
dev-dependencies = []

